"""add activo to usuario

Revision ID: 83232153839b
Revises: bb02e35d63df
Create Date: 2026-04-23 00:40:14.753636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83232153839b'
down_revision: Union[str, None] = 'bb02e35d63df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_unique_constraint(None, 'usuario_rol', ['usuario_id', 'rol_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario_rol', type_='unique')
    op.drop_column('usuario', 'activo')
    # ### end Alembic commands ###
